chunking:
  max_rows: 15
  max_tokens: 500
  min_tokens: 40
embeddings:
  embeddings_batch_size: 32
model_name: sentence-transformers/all-MiniLM-L6-v2
faiss_index_path: data/faiss.index
raw_data_path: "/home/athenaik/MASTER_THESIS/data/raw"
extracted_data_path: "/home/athenaik/MASTER_THESIS/data/extracted"
processed_data_path: "/home/athenaik/MASTER_THESIS/data/processed"
embeddings_data_path: "/home/athenaik/MASTER_THESIS/data/embeddings"
test_data_path: "/home/athenaik/MASTER_THESIS/data/test_data/test_questions.jsonl"
top_k: 5
graph_rag:
  neo4j:
    uri: "neo4j+s://50d89f74.databases.neo4j.io"
    user: "neo4j"
    password: "Xi-9J1fP7m6Xo0hsfuTkrAOLP5H3FrpDQlWCx1isKjk"   
paths:
  graph_data: "/home/athenaik/MASTER_THESIS/data/graphrag/raw/train.json"
  logs: "logs"
sft_paths:
  train_raw_sft_data: "/home/athenaik/MASTER_THESIS/data/sft/raw/train.json"
  val_raw_sft_data: "/home/athenaik/MASTER_THESIS/data/sft/raw/val.json"
  test_raw_sft_data: "/home/athenaik/MASTER_THESIS/data/sft/raw/test.json"
  processed_sft_path: "/home/athenaik/MASTER_THESIS/data/sft/processed"